services:
  luftfartshinder:
    image: ${DOCKER_REGISTRY-}luftfartshinder
    restart: always
    build:
      context: .
      dockerfile: Luftfartshinder/Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080/
      - ConnectionStrings__DbConnection=Server=mariadb;Database=Kartverketdb;User=root;Password=root123
      - ConnectionStrings__AuthConnection=Server=mariadb;Database=AuthKartverketdb;User=root;Password=root123
    depends_on:
      - mariadb
        # condition: service_healthy

  
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
  
volumes:
    mariadb_data:

